disabled_rules:
  - line_length # NOTE: Devs, if possible, break the long lines into multiple short ones
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name # NOTE: Disable the violation for `rx_*` variables & constants
  - large_tuple # NOTE: Devs, this rule is disabled because of the Rx tuple usage. If possible, create custom struct to store the values
  - control_statement # NOTE: Many control statements are included in parentheses (old school style, probably adopted from the Objective-C control flow)
  - todo # NOTE: Keep the // TODO: comments

excluded:
  - Pods
