# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_version
    push_git_tag
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app(workspace: "ModernWallet.xcworkspace", scheme: "ModernMoney.Test")
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Example.xcodeproj"
    )
    upload_to_testflight
  end

  desc "Increment build version"
  lane :increment_build_version do
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "ModernWallet.xcodeproj"
    )
  end

  desc "Push git tag"
  lane :push_git_tag do
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    increment_build_version

    # Commit the version bump
    commit_version_bump(xcodeproj: "ModernWallet.xcodeproj")

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    add_git_tag

    # Push the new commit and tag back to your git remote
    #push_to_git_remote
  end
end
